const assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const {chromium}=require(process.env.DSB_PLAYWRIGHT_PATH||'playwright');
const {startServer}=require('../server');
const PNG='data:image/png;base64,'+fs.readFileSync(path.join(__dirname,'..','assets','dsb.png')).toString('base64');
async function main(){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dsb-crm-ui-')),qa=path.join(__dirname,'..','tmp','crm-qa');fs.mkdirSync(qa,{recursive:true});
  const customers=[{id:'middle',company:'Desert Supply LLC',name:'Jane Smith',email:'jane@desert.example',phone:'+971 12345678',tradeRegion:'中东',region:'UAE',grade:'A',status:'待研究',website:'https://desert.example'},{id:'sea',company:'Ocean & Co',email:'info@ocean.example',tradeRegion:'东南亚',region:'Singapore',grade:'B',status:'待研究'},{id:'eu',company:'European Tools',email:'john@eu.example',tradeRegion:'欧洲',grade:'C',status:'待研究'}];
  const products=[{id:'p1',name:'Industrial Pump',englishName:'Pump',sku:'PUMP-88',price:120,unit:'PCS',assets:[{name:'product.png',data:PNG}]},{id:'p2',name:'Safety Valve',sku:'VALVE-22',price:80,unit:'PCS'}];
  fs.writeFileSync(path.join(dir,'workspace-data.json'),JSON.stringify({version:2,customers,products,documents:[],templates:[],campaigns:[]}));
  const s=await startServer({port:0,configDir:dir});const browser=await chromium.launch({channel:'msedge',headless:true});const p=await browser.newPage({viewport:{width:1480,height:940}}),errors=[];p.on('pageerror',err=>errors.push(err.message));
  const api=async(route,body)=>{const r=await fetch(s.url+'/api/workspace/'+route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return r.json();};
  try{
    await p.route('**/api/workspace/rates',r=>r.fulfill({json:{rates:{USD:1,CNY:7.1,EUR:.9,GBP:.77,AED:3.67},at:'Fixture',cached:true}}));
    await p.goto(s.url);await p.getByRole('heading',{name:'客户跟进',exact:true}).waitFor();
    await p.locator('[data-page=customers]').click();assert.equal(await p.locator('#customerRows tr').count(),3);for(const region of ['北美','南美','澳洲/大洋洲','西非','南亚'])assert.equal(await p.locator(`.toolbar [data-trade-filter="${region}"]`).count(),1);
    await p.locator('.toolbar .region-filter summary').click();await p.locator('.toolbar [data-trade-filter="中东"]').check();await p.locator('.toolbar [data-trade-filter="东南亚"]').check();assert.equal(await p.locator('#customerRows tr').count(),2);
    assert(await p.locator('th [data-trade-filter="中东"]').isChecked());
    await p.locator('[data-action="followUp:middle"]').click();await p.locator('#modal [name=nextFollowUp]').fill('2026-10-15T19:30');await p.locator('#modal [name=followUpNotes]').fill('确认技术参数，再安排报价');await p.locator('#modalForm button[type=submit]').click();await p.locator('#modal').waitFor({state:'hidden'});assert((await p.locator('[data-action="followUp:middle"]').innerText()).includes('19:30'));assert.equal(await p.locator('#customerRows tr').count(),2);
    await p.screenshot({path:path.join(qa,'customers-follow-up-regions.png'),fullPage:true});
    await p.locator('[data-page=verify]').click();await p.locator('[name=guessName]').fill('Jane Smith');await p.locator('[name=guessDomain]').fill('desert.example');await p.locator('[data-action=generateCandidates]').click();assert(await p.locator('#candidateOutput').getByText('jane.smith@desert.example',{exact:true}).count());await p.locator('[data-action=importCandidates]').click();assert((await p.locator('[name=verifyEmails]').inputValue()).includes('jane.smith@desert.example'));
    await p.route('**/api/workspace/verify',async r=>{const emails=r.request().postDataJSON().emails;const results=emails.map((email,i)=>({email,status:i===0?'valid':'invalid',label:i===0?'可发送':'无效',reasons:['UI fixture']}));const data=JSON.parse(fs.readFileSync(path.join(dir,'workspace-data.json')));data.emailChecks=Object.fromEntries(results.map(x=>[x.email,{...x,at:new Date().toISOString()}]));fs.writeFileSync(path.join(dir,'workspace-data.json'),JSON.stringify(data));await r.fulfill({json:{results}});});
    await p.locator('[data-action=verifyCandidates]').click();await p.locator('#modal [name=mode]').waitFor();await p.locator('#modal [name=mode]').selectOption('existing');await p.locator('#modal [name=customerId]').selectOption('middle');await p.locator('#modal [name=phone]').fill('+971 99887766');await p.locator('#modalForm button[type=submit]').click();await p.locator('#modal').waitFor({state:'hidden'});assert((await api('state')).customers.some(x=>x.email==='jane@desert.example'&&x.phone==='+971 99887766'));
    await p.screenshot({path:path.join(qa,'email-rules-validation.png'),fullPage:true});
    await p.locator('[data-page=products]').click();assert.equal(await p.locator('[data-product=p1] img.product-thumb').count(),1);await p.screenshot({path:path.join(qa,'product-thumbnails.png'),fullPage:true});
    await p.locator('[data-page=documents]').click();await p.locator('[data-action="doc:QT"]').click();await p.locator('[data-doc-tab=parties]').click();await p.locator('[data-picker-input=docCustomer]').fill('jane desert');assert.equal(await p.locator('#docCustomerOptions [role=option]').count(),1);await p.locator('#docCustomerOptions [role=option]').click();assert.equal(await p.locator('[name="buyer.company"]').inputValue(),'Desert Supply LLC');
    await p.locator('[data-doc-tab=items]').click();await p.locator('[data-picker-input=docProduct]').fill('PUMP-88');assert.equal(await p.locator('#docProductOptions [role=option]').count(),1);await p.screenshot({path:path.join(qa,'document-product-search.png'),fullPage:true});await p.locator('[data-picker-input=docProduct]').press('ArrowDown');await p.locator('[data-picker-input=docProduct]').press('Enter');await p.locator('[name="items.0.name"]').waitFor();assert.equal(await p.locator('[name="items.0.name"]').inputValue(),'Industrial Pump');await p.locator('#showProductImages').check();await p.frameLocator('#docPreview').locator('table img').waitFor();
    await p.locator('[data-action=saveDoc]').click();await p.frameLocator('#docPreview').locator('table img').waitFor();await p.screenshot({path:path.join(qa,'quotation-product-image.png'),fullPage:true});const doc=(await api('state')).documents[0];assert(doc.showProductImages);assert(doc.items[0].image.startsWith('data:image/png;'));
    await p.locator('#showProductImages').uncheck();await p.frameLocator('#docPreview').locator('table img').waitFor({state:'detached'});await p.locator('[data-action=saveDoc]').click();assert.equal((await api('state')).documents[0].showProductImages,false);
    await p.locator('[data-page=mail]').click();await p.locator('[data-recipient=middle]').check();await p.locator('[data-recipient=sea]').check();await p.locator('[name=mailSubject]').fill('For {公司}');await p.locator('#mailEditor').fill('Dear Someone,\nIndustrial product details.');await p.locator('[data-action=previewMail]').click();await p.locator('[name=previewRecipient]').selectOption('sea');await p.frameLocator('#mailPreview').getByText(/Dear Ocean & Co,/).waitFor();assert.equal(await p.locator('#previewSubject').innerText(),'For Ocean & Co');await p.screenshot({path:path.join(qa,'personalized-mail-preview.png'),fullPage:true});await p.locator('#modal [data-action=close]').first().click();
    // Dialogs and notifications must leave the editor writable, with the caret restored.
    await p.locator('#mailEditor').click();await p.locator('#mailEditor').press('Control+End');await p.keyboard.type(' BEFORE');
    await p.locator('[data-action=previewMail]').click();await p.locator('#modal [data-action=close]').first().click();await p.waitForFunction(()=>document.activeElement?.id==='mailEditor');await p.keyboard.type(' AFTER_PREVIEW');assert((await p.locator('#mailEditor').innerText()).includes('BEFORE AFTER_PREVIEW'));
    await p.locator('[data-action=mailLink]').click();await p.locator('#modal [name=url]').fill('https://example.com/spec');await p.locator('#modal [name=label]').fill('Specification');await p.locator('#modalForm button[type=submit]').click();await p.locator('#modal').waitFor({state:'hidden'});await p.waitForFunction(()=>document.activeElement?.id==='mailEditor');await p.keyboard.type(' AFTER_LINK');assert((await p.locator('#mailEditor').innerText()).includes('AFTER_LINK'));
    await p.locator('[data-action=aiMail]').click();await p.locator('#modal [data-action=close]').first().click();await p.waitForFunction(()=>document.activeElement?.id==='mailEditor');await p.keyboard.type(' AFTER_AI_CANCEL');
    await p.route('**/api/workspace/smtp-test',r=>r.fulfill({status:500,json:{error:'SMTP test fixture error'}}));await p.locator('[data-action=smtpTest]').click();await p.waitForFunction(()=>document.activeElement?.id==='mailEditor');await p.keyboard.type(' AFTER_NOTICE');assert((await p.locator('#mailEditor').innerText()).includes('AFTER_NOTICE'));
    await p.locator('[data-action=sendMail]').click();await p.getByRole('heading',{name:'确认发送邮件'}).waitFor();await p.locator('#modal [data-action=close]').first().click();await p.waitForFunction(()=>document.activeElement?.id==='mailEditor');await p.keyboard.type(' AFTER_SEND_CANCEL');assert((await p.locator('#mailEditor').innerText()).includes('AFTER_SEND_CANCEL'));
    await p.route('**/api/workspace/discovery/start',r=>r.fulfill({json:{id:'fixture-batch',status:'running',phase:'AI 检索中',items:[],warnings:[]}}));
    await p.route('**/api/workspace/discovery/batch?*',r=>r.fulfill({json:{id:'fixture-batch',status:'complete',phase:'开发完成',criteria:{industry:'Industrial',region:'UAE'},items:[{itemId:'fixture-item',company:'Fixture Public Co',website:'https://fixture.example',name:'',phone:'',email:'',tradeRegion:'中东',region:'UAE',customerNumber:'DSB-FIXTURE',importState:'已入库',customerId:'fixture-id',sources:[{url:'https://fixture.example/contact',title:'Contact'}]}],warnings:[]}}));
    await p.locator('[data-page=discovery]').click();await p.locator('#discoveryForm2 [name=industry]').fill('Industrial');await p.locator('#discoveryForm2 [name=region]').fill('UAE');await p.locator('#discoveryForm2 button[type=submit]').click();await p.getByText('Fixture Public Co',{exact:true}).waitFor();await p.locator('[data-action=selectDiscovered]').click();assert(await p.locator('[data-discovery-item=fixture-item]').isChecked());await p.screenshot({path:path.join(qa,'ai-discovery-results.png'),fullPage:true});
    assert.deepEqual(errors,[]);console.log('PASS: multi-region filters and synchronized header, direct follow-up edit, generated candidates and verification company dialog, thumbnails, client/product keyword + keyboard search, persisted quote image toggle, personalized per-recipient preview, discovery list selection; screenshots '+qa);
  }finally{await browser.close();await new Promise(r=>s.server.close(r));}
}
main().catch(err=>{console.error(err);process.exitCode=1;});
