const fs=require('fs');const path=require('path');const os=require('os');
const {chromium}=require(process.env.DSB_PLAYWRIGHT_PATH||'playwright');
const {startServer}=require('../server');
async function main(){const configDir=fs.mkdtempSync(path.join(os.tmpdir(),'dsb-ui-'));const s=await startServer({port:0,configDir});const browser=await chromium.launch({channel:'msedge',headless:true});const p=await browser.newPage({viewport:{width:1480,height:940}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
  await p.route('**/api/workspace/rates',route=>route.fulfill({json:{rates:{USD:1,CNY:7.1,EUR:.9,GBP:.77,AED:3.67},at:'UI test fixture',source:'Test data',cached:true}}));
  await p.goto(s.url);await p.getByRole('heading',{name:'客户跟进',exact:true}).waitFor();
  const dir=path.join(__dirname,'..','tmp','dsb-qa');fs.mkdirSync(dir,{recursive:true});await p.screenshot({path:path.join(dir,'home-desktop.png'),fullPage:true});
  await p.locator('[data-page="customers"]').click();await p.locator('[data-action="newCustomer"]').click();await p.locator('[name="company"]').fill('Ocean Supply Ltd');await p.locator('[name="name"]').fill('Jane Smith');await p.locator('[name="email"]').fill('jane@example.com');await p.locator('[name="grade"]').selectOption('A');await p.locator('#modalForm button[type=submit]').click();await p.getByText('Ocean Supply Ltd',{exact:true}).waitFor();await p.reload();await p.locator('[data-page="customers"]').click();await p.getByText('Ocean Supply Ltd',{exact:true}).waitFor();
  await p.screenshot({path:path.join(dir,'customers.png'),fullPage:true});
  await p.locator('[data-page="products"]').click();await p.locator('[data-action="newProduct"]').click();await p.locator('#productForm [name="name"]').fill('Oil spill containment boom');await p.locator('#productForm [name="sku"]').fill('BOOM-01');await p.locator('#productForm [name="price"]').fill('120');await p.locator('button[form="productForm"]').click();await p.getByRole('heading',{name:'Oil spill containment boom'}).waitFor();
  await p.locator('[data-page="documents"]').click();await p.locator('[data-action="doc:QT"]').click();await p.locator('[data-doc-tab="parties"]').click();await p.locator('[data-picker-input=docCustomer]').fill('Ocean Supply');await p.locator('#docCustomerOptions [role=option]').click();await p.locator('[data-doc-tab="items"]').click();await p.locator('[data-picker-input=docProduct]').fill('BOOM-01');await p.locator('#docProductOptions [role=option]').click();await p.locator('[name="items.0.quantity"]').fill('10');await p.locator('[data-action="saveDoc"]').click();await p.frameLocator('#docPreview').getByRole('heading',{name:/QUOTATION/}).waitFor();await p.frameLocator('#docPreview').getByText('TOTAL USD 1200.00').waitFor();await p.screenshot({path:path.join(dir,'quotation.png'),fullPage:true});
  for(const page of ['templates','mail','discovery','verify','settings']){await p.locator(`[data-page="${page}"]`).click();await p.screenshot({path:path.join(dir,page+'.png'),fullPage:true});}
  await p.locator('[data-page="home"]').click();await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(dir,'home-mobile.png'),fullPage:true});
  const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)throw new Error('Mobile page overflow');if(errors.length)throw new Error(errors.join('\n'));console.log('PASS: browser creation/reload, product save, quote customer/product linkage, total preview, all pages, mobile width; screenshots '+dir);
}finally{await browser.close();await new Promise(r=>s.server.close(r));}}
main().catch(e=>{console.error(e);process.exitCode=1;});
